### ISSUE TITLE
Factorio 0.17 build

### ISSUE THREAD

**Issue by benjamin-pilgrim** [V453000/Absorbed-Beacons#1]
Any chance of getting a factorio 0.17 build of this mod? I'd like to play with it on a map that has other mods not yet updated to 0.18.

**Comment by V453000** [comment]
I think the problem are a few icon definitions... I might have a look into it, but not sure.

**Comment by V453000** [comment]
Hm, I don't know how I would release this, I can't put 0.0.1 on mod portal again and 0.0.2 for 0.17 sounds really odd. On top of that the graphics will look out of place in 0.17. Please just stick with 0.18.
